---

repository:
  name: chorus-dcl
  description: Lickd Chorus DCL library
  homepage: https://github.com/lickdltd/chorus-dcl
  topics: lickd, chorus, dcl, decentraland
  private: false
  has_issues: false
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
teams:
  - name: engineering
    permission: admin
branches:
  - name: main
    protection: 
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: [ ]
          teams: [ ]
      required_status_checks:
        strict: false
        contexts:
          - Build
      enforce_admins: false
      required_linear_history: true
      restrictions:
        apps: [ ]
        users: [ ]
        teams: [ ]
